on:
  pull_request:
    types: [opened, edited, reopened]

name: Build the photo wall

jobs:
  build-photos:
    name: Prepping the photos
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: update-photos
      uses: ./action
